services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: noc_composite_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - noc_network

    nginx:
        image: nginx:alpine
        container_name: noc_nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - noc_network

networks:
    noc_network:
